# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemandDriver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for DemandDriver

  target 'DemandDriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemandDriverUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
